# Generated by Django 3.1.6 on 2021-02-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('block_no', models.CharField(max_length=1, null=True)),
                ('capacity', models.IntegerField(default=3)),
                ('vacancy', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('join_year', models.IntegerField(default=2016)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('father_name', models.CharField(max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('fee_receipt', models.FileField(null=True, upload_to='receipt/')),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(default=382009)),
                ('roll_no', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.room')),
            ],
        ),
    ]
