# Generated by Django 3.1.6 on 2021-03-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('accept', models.BooleanField(default=False)),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student1', to='hostel.student')),
                ('student2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student2', to='hostel.student')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student')),
            ],
        ),
    ]
