# Generated by Django 3.1.6 on 2021-03-17 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hostel', '0002_change_swap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('is_student', models.BooleanField(default=True)),
            ],
        ),
    ]
